name = "Cart Drawer"
uid = "a6d6e8e8-9457-cab6-728c-071caf4f11ad51802e26"
type = "theme"

[[extensions]]
name = "Cart Drawer App"
handle = "cart-drawer-app"
type = "theme_app_extension"

[[extensions.blocks]]
name = "Cart Drawer"
type = "shopify://theme-app-extension/blocks/cart-drawer"
handle = "cart-drawer"
target = "body"
